# Generated by Django 5.0.4 on 2024-04-20 02:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('titulo', models.CharField(max_length=100)),
                ('rubro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='takin.persona')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            bases=('takin.persona',),
        ),
        migrations.CreateModel(
            name='Empleador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='takin.persona')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Empleador',
            },
            bases=('takin.persona',),
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulantes', to='takin.contrato')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='takin.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Empleado', models.ManyToManyField(related_name='oficios', to='takin.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='empleador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='takin.empleador'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='takin.contrato')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='takin.empleado')),
                ('empleador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='takin.empleador')),
            ],
        ),
    ]
