# Generated by Django 5.0.4 on 2024-04-19 06:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    
    initial = True
    dependencies = [
        ('takin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('titulo', models.CharField(max_length=100)),
                ('rubro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='oficio1',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='oficio2',
        ),
        migrations.AddField(
            model_name='empleado',
            name='contraseña',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='genero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='contratos',
            field=models.ManyToManyField(related_name='empleados', to='takin.contrato'),
        ),
        migrations.CreateModel(
            name='Empleador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(default='s', max_length=100)),
                ('contratos', models.ManyToManyField(related_name='empleadores', to='takin.contrato')),
                ('persona', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='takin.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='takin.empleado')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='takin.contrato')),
                ('empleador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='takin.empleador')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='oficios',
            field=models.ManyToManyField(related_name='empleados', to='takin.oficio'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='persona',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='takin.persona'),
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulantes', to='takin.contrato')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='takin.empleado')),
            ],
        ),
    ]
