# Generated by Django 5.0.4 on 2024-04-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='oficios',
            field=models.ManyToManyField(default=None, null=True, related_name='empleados', to='takin.oficio'),
        ),
    ]
