# Generated by Django 5.0.4 on 2024-04-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='empleador',
            old_name='contraseña',
            new_name='password',
        ),
    ]
