# Generated by Django 5.0.4 on 2024-04-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takin', '0002_rename_contraseña_empleado_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='empleador',
            old_name='correo',
            new_name='email',
        ),
    ]
