# Generated by Django 5.0.4 on 2024-04-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takin', '0003_rename_correo_empleado_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='empleador',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='edad',
        ),
    ]
