# Generated by Django 5.0.4 on 2024-04-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takin', '0003_alter_empleado_oficios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleador',
            name='contratos',
            field=models.ManyToManyField(blank=True, default=[], related_name='empleadores', to='takin.contrato'),
        ),
        migrations.AlterField(
            model_name='empleador',
            name='ubicacion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
